//==================================================
//     Outputs that match the input variables
//==================================================
output "delegate_account_id" {
  description = "The value of the `delegate_account_id` input variable."
  value       = var.delegate_account_id
}

output "max_session_duration" {
  description = "The value of the `max_session_duration` input variable."
  value       = var.max_session_duration
}


//==================================================
//       Outputs generated by this module
//==================================================
output "iam_role_read" {
  description = "The `aws_iam_role` resource that was created that has read-only permissions. You shouldn't need to use this output anywhere, it's just made available in case you want to do advanced funky things with it."
  value       = aws_iam_role.delegate_read
}

output "iam_role_write" {
  description = "The `aws_iam_role` resource that was created that has write permissions. You shouldn't need to use this output anywhere, it's just made available in case you want to do advanced funky things with it."
  value       = aws_iam_role.delegate_write
}
